listenAddress = ":27333"
domainName = "localhost:27333"

bigqueryEnabled = false
bigqueryDataset = "access_logs"

redisEnabled = false
redisEndpoint = "10.51.202.235:6379"

cloudStorageEnabled = true
cloudStorageBucket = "ent-objects-1"

projectID = "oak-ci"

ginMode = "debug"
logLevel = "debug"

[[users]]
ID = 1
Name = "user"
APIKey = "oAf1MTownkbSkMuCQVUIrNbS4GxKlBsDAQVKEihfajMoPiWreyhmtmVRVPVGOmJUJJAsfrYVtfVqBpGbX3BaZw=="
CanRead = true
CanWrite = true

[[users]]
ID = 2
Name = "public"
APIKey = ""
CanRead = true
CanWrite = false
