listenAddress = ":27333"
domainName = "localhost:27333"

bigqueryEnabled = false
bigqueryDataset = "access_logs"

redisEnabled = false
redisEndpoint = "10.51.202.235:6379"

cloudStorageEnabled = false

ginMode = "debug"

[[users]]
ID = 1
Name = "user"
APIKey = "xxx"
CanRead = true
CanWrite = true
