#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o xtrace
set -o pipefail

export BIGQUERY_DATASET=access_logs
export DOMAIN_NAME=localhost:27333

go run github.com/google/ent/cmd/ent-web -config=ent-web.toml
